stages:
    - build
  
link-checker-mlc:
    stage: build
    image: rust:latest
    script:
        - curl -L https://github.com/becheran/mlc/releases/download/v0.7.0/mlc -o mlc
        - chmod +x mlc
        - ./mlc --ignore-links "http*://crates.io*"
    allow_failure: true

build-rust-nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
        - cargo build --verbose
        - cargo test --verbose