[package]
name = "wildmatch"
version = "1.0.3"
authors = ["Armin Becher <armin.becher@gmail.com>"]
edition = "2018"
description = "Simple string matching  with questionmark and star wildcard operator."
keywords = [ "globbing", "matching", "questionmark", "star", "string-matching"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/becheran/wildmatch"

[dependencies]

[dev-dependencies]
ntest = "0.4.1"
